name = "BammannChiesaJohnsonPlasticity"
uuid = "056ed34d-f5e1-4b0f-b3f6-c7e5e8ee168e"
authors = ["Joby M. Anthony III"]
version = "0.0.0-dev"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ContinuumMechanicsBase = "3a778109-d974-46c8-ac54-09f30d605bdf"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"

[extensions]
OptimizationBCJPlasticityExt = ["Optimization"]

[compat]
ComponentArrays = "0.15.24"
ContinuumMechanicsBase = "0.2.2"
DocStringExtensions = "0.9.3"
LinearAlgebra = "1.11.0"
StructArrays = "0.7.0"
Tensors = "1.16.1"
Test = "1.11.0"
julia = "1.11"

[extras]
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OptimizationOptimJL", "LossFunctions"]
